## STAGE 1: build

FROM node:15.11.0-alpine3.10

## Storing node modules on a separate layer will prevent unnecessary npm installs at each build.
WORKDIR /app

COPY . .
#update package-lock.json file
RUN npm i && npm run build-prod

## STAGE 2: Setup

FROM nginx:1.18.0
RUN sed -i 's|index  index.html index.htm;|try_files $uri /index.html;|' /etc/nginx/conf.d/default.conf

COPY --from=0  /app/dist/LeavePlannerApp /usr/share/nginx/html

EXPOSE 80
